export const CURRENCY_RUB = 'RUB',
  CURRENCY_USD = 'USD',
  CURRENCY_EUR = 'EUR',

  OP_DEBIT = 'OP_DEBIT',
  OP_CREDIT = 'OP_CREDIT',
  OP_INTEREST = 'OP_INTEREST',
  OP_OPENING_DEPOSIT = 'OP_OPENING_DEPOSIT',
  OP_DEPOSIT = 'OP_DEPOSIT';
